### ISSUE TITLE
Penultimate version - checklist

### ISSUE THREAD

**Issue by bpbond** [jinshijian/GlobalC#83]
- [ ] Redo figures' color #82 
- [ ] FLUXNET methods text - @bpbond 
- [ ] CMIP processing methods text - @kdorheim 
- [ ] Overlap groups - mean calculation, put in text #81  @jinshijian 
- [ ] GPP figure - redo with point + different groups labels  @jinshijian 
- [ ] Finalize Figure 2 #70  @bpbond and @kdorheim 
- [ ] Literature to read (at least for me): [Kondo et al.](https://github.com/jinshijian/GlobalC/issues/48#issuecomment-564994496),  [Lovenduski 2017](https://iopscience.iop.org/article/10.1088/1748-9326/aa66b8), Battle et al., ...?
- [ ] Check with Alex about CARDAMOM #4 
- [ ] Go through text and clean up/incorporate co-authors' comments
- [ ] Table 1 - clean up
- [ ] End of manuscript - finalize

Finally:

- [ ] Citations - go through and make final decisions on which we want or don't
- [ ] Transfer repo to TES

**Comment by jinshijian** [comment]
Some other points:
1. All figures (including supplemental figures) need to be mentioned in the main text?
2. Using srdb_v5?
3. Added Rh:GPP ratio in figure 3?

**Comment by bpbond** [comment]
>All figures (including supplemental figures) need to be mentioned in the main text?

Yes, let's definitely check this.

>Using srdb_v5 (save for later)?

I'd vote no. Save for later.

>Added Rh:GPP ratio in figure 3?

Seems like it'll make it more complicated and perhaps confusing, but let's discuss.

>is it possible to see seed and have the same results for multiple runs?

Yes, `set.seed(...)` does this.

**Comment by bpbond** [comment]
One thing we might do re Rh:GPP is take a look at [Shao et al. (2013)](http://dx.doi.org/10.1088/1748-9326/8/3/034034) - they looked at Rh for CMIP5 models.

**Comment by bpbond** [comment]
@jinshijian I have gone through cover letter and provide a lot of suggestions. Please look and understand _why_ (i.e. don't just accept blindly), using your own judgment.

Otherwise...Monday morning let's go through the manuscript again together? Then we can put it into Information Release I think, take care of a few other odds and ends. Sound good?

**Comment by bpbond** [comment]
@jinshijian One thing I realized is that the discussion doesn't really touch on Figure 2 and models at all. Do we want to? 🤔

**Comment by jinshijian** [comment]
Does not touch on Figure 2 is a problem.

**Comment by bpbond** [comment]
Final version things to consider:

- Is Figure 2 distinct enough from Figure 1?
- Are Figures 2 and 3 referenced (enough) in discussion?
